
baseURL = 'https://jfgrea27.github.io/'
languageCode = 'en-uk'
title = 'James Rea Blog'


[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'light'
colorPalette = 'gruvebox'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
Hello! I'm James, a software engineer exploring **AI**, **distributed systems**, and all things code, and this is where I will write my findings!

My website is organised into the following:

- `blog` - where I discuss cool projects, thoughts and opinions;
- `til` - where I frequently add today-i-learns
- `journey` - where I dump any career/tech decisions made. 
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

faviconPath = './favicon'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/james-rea/"

[[params.social]]
name = "github"
url = "https://github.com/jfgrea27"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "til"
url = "/til"

[[params.menu]]
name = "journey"
url = "/journey"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark.renderer]
unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"


[module]
[[module.imports]]
path = "github.com/tomfran/typo"
